services:
  caddy:
    image: caddy:2
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - default
      - tutor-iblchat-network

  flowise:
    image: flowiseai/flowise:latest
    ports:
      - "3000:3000"
    volumes:
      - ./flowise_data:/root/.flowise 
    environment:
      - PORT=3000
      - EXECUTION_MODE=main
    env_file:
      - .env.${ENVIRONMENT:-development}  
    depends_on:
      - ollama  
    networks:
      - default
      - tutor-iblchat-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama-data:/root/.ollama
    networks:
      - default
      - tutor-iblchat-network


  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=ibaldb
      - POSTGRES_USER=ibaluser
      - POSTGRES_PASSWORD=ibalpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  backend:
    build: ./backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8000 llm_websocket_api.asgi:application"
    volumes:
      - ./backend:/app/backend
      - backend_data:/app/backend_data
    ports:
      - "8000:8000"
    env_file:
      - .env.${ENVIRONMENT:-development}
    environment:
      - ENV_FILE=.env.${ENVIRONMENT:-development}
    depends_on:
      - redis
      - flowise
      - db
    networks:
      - default
      - tutor-iblchat-network
    extra_hosts:
      - "local.openedx.io:host-gateway"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - default

networks:
  default:
    driver: bridge
  tutor-iblchat-network:
    external: true

volumes:
  backend_data:
  redis_data:
  postgres_data:
