# Generated by Django 5.2.3 on 2025-06-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth2", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oauth2client",
            name="client_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="oauth2client",
            name="client_secret",
            field=models.CharField(max_length=255),
        ),
    ]
