# Generated by Django 5.2 on 2025-06-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth2", "0002_alter_oauth2client_client_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauth2authorizationcode",
            name="redirect_uri",
            field=models.URLField(default=""),
        ),
    ]
