# Generated by Django 5.2.3 on 2025-06-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oauth2", "0003_oauth2authorizationcode_redirect_uri"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oauth2authorizationcode",
            name="client",
        ),
        migrations.RemoveField(
            model_name="oauth2authorizationcode",
            name="user",
        ),
        migrations.RemoveField(
            model_name="oauth2token",
            name="user",
        ),
        migrations.DeleteModel(
            name="OAuth2Client",
        ),
        migrations.DeleteModel(
            name="OAuth2AuthorizationCode",
        ),
        migrations.DeleteModel(
            name="OAuth2Token",
        ),
    ]
